---

- name: "Disable swap and selinux"
  command: "{{ item }}"
  become: yes
  loop:
    - swapoff -a
    - sed -i '/swap/d' /etc/fstab
    - sed -i s/=enforcing/=disabled/g /etc/selinux/config

- name: "Get repos"
  command: "{{ item }}"
  become: yes
  loop:
    - wget -O /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
    - wget -O /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo

- name: "Copying files"
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: 'kubernetes.repo', dest: '/etc/yum.repos.d/kubernetes.repo' }
    - { src: 'crio.conf', dest: '/etc/modules-load.d/crio.conf' }
    - { src: 'k8s.conf', dest: '/etc/sysctl.d/k8s.conf' }

- name: "Ensure firewall starts on boot"
  firewalld:
    permanent: yes
    masquerade: yes
    state: enabled
  become: yes
  notify: reload firewalld

- name: "Install k8s_deps"
  dnf:
    name: "{{ k8s_deps }}"
    state: present
  become: yes

- name: "Install k8s"
  command: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  become: yes

- name: "Ensure services are started"
  become: yes
  service:
    name: "{{ item }}"
    state: started
  loop:
    - firewalld
    - crio
    - kubelet

- name: "Ensure services are enabled"
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - firewalld
    - crio
    - kubelet

- name: "Enable transparent masquerading"
  command: modprobe br_netfilter
  become: yes

- name: "Reboot"
  reboot:
  become: yes